/*
 * Slurm Rest API
 *
 * API to access and control Slurm DB.
 *
 * API version: dbv0.0.37
 * Contact: sales@schedmd.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmdbrest

import (
	"encoding/json"
)

// Dbv0037AssociationMaxPerAccount Max per accounting settings
type Dbv0037AssociationMaxPerAccount struct {
	// Max wallclock per account
	WallClock *int32 `json:"wall_clock,omitempty"`
}

// NewDbv0037AssociationMaxPerAccount instantiates a new Dbv0037AssociationMaxPerAccount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDbv0037AssociationMaxPerAccount() *Dbv0037AssociationMaxPerAccount {
	this := Dbv0037AssociationMaxPerAccount{}
	return &this
}

// NewDbv0037AssociationMaxPerAccountWithDefaults instantiates a new Dbv0037AssociationMaxPerAccount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDbv0037AssociationMaxPerAccountWithDefaults() *Dbv0037AssociationMaxPerAccount {
	this := Dbv0037AssociationMaxPerAccount{}
	return &this
}

// GetWallClock returns the WallClock field value if set, zero value otherwise.
func (o *Dbv0037AssociationMaxPerAccount) GetWallClock() int32 {
	if o == nil || o.WallClock == nil {
		var ret int32
		return ret
	}
	return *o.WallClock
}

// GetWallClockOk returns a tuple with the WallClock field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0037AssociationMaxPerAccount) GetWallClockOk() (*int32, bool) {
	if o == nil || o.WallClock == nil {
		return nil, false
	}
	return o.WallClock, true
}

// HasWallClock returns a boolean if a field has been set.
func (o *Dbv0037AssociationMaxPerAccount) HasWallClock() bool {
	if o != nil && o.WallClock != nil {
		return true
	}

	return false
}

// SetWallClock gets a reference to the given int32 and assigns it to the WallClock field.
func (o *Dbv0037AssociationMaxPerAccount) SetWallClock(v int32) {
	o.WallClock = &v
}

func (o Dbv0037AssociationMaxPerAccount) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.WallClock != nil {
		toSerialize["wall_clock"] = o.WallClock
	}
	return json.Marshal(toSerialize)
}

type NullableDbv0037AssociationMaxPerAccount struct {
	value *Dbv0037AssociationMaxPerAccount
	isSet bool
}

func (v NullableDbv0037AssociationMaxPerAccount) Get() *Dbv0037AssociationMaxPerAccount {
	return v.value
}

func (v *NullableDbv0037AssociationMaxPerAccount) Set(val *Dbv0037AssociationMaxPerAccount) {
	v.value = val
	v.isSet = true
}

func (v NullableDbv0037AssociationMaxPerAccount) IsSet() bool {
	return v.isSet
}

func (v *NullableDbv0037AssociationMaxPerAccount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDbv0037AssociationMaxPerAccount(val *Dbv0037AssociationMaxPerAccount) *NullableDbv0037AssociationMaxPerAccount {
	return &NullableDbv0037AssociationMaxPerAccount{value: val, isSet: true}
}

func (v NullableDbv0037AssociationMaxPerAccount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDbv0037AssociationMaxPerAccount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


