/*
 * Slurm Rest API
 *
 * API to access and control Slurm DB.
 *
 * API version: dbv0.0.37
 * Contact: sales@schedmd.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmdbrest

import (
	"encoding/json"
)

// Dbv0037TresInfo struct for Dbv0037TresInfo
type Dbv0037TresInfo struct {
	// Slurm errors
	Errors *[]Dbv0037Error `json:"errors,omitempty"`
	// Array of tres
	Tres *[][]map[string]interface{} `json:"tres,omitempty"`
}

// NewDbv0037TresInfo instantiates a new Dbv0037TresInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDbv0037TresInfo() *Dbv0037TresInfo {
	this := Dbv0037TresInfo{}
	return &this
}

// NewDbv0037TresInfoWithDefaults instantiates a new Dbv0037TresInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDbv0037TresInfoWithDefaults() *Dbv0037TresInfo {
	this := Dbv0037TresInfo{}
	return &this
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *Dbv0037TresInfo) GetErrors() []Dbv0037Error {
	if o == nil || o.Errors == nil {
		var ret []Dbv0037Error
		return ret
	}
	return *o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0037TresInfo) GetErrorsOk() (*[]Dbv0037Error, bool) {
	if o == nil || o.Errors == nil {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *Dbv0037TresInfo) HasErrors() bool {
	if o != nil && o.Errors != nil {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []Dbv0037Error and assigns it to the Errors field.
func (o *Dbv0037TresInfo) SetErrors(v []Dbv0037Error) {
	o.Errors = &v
}

// GetTres returns the Tres field value if set, zero value otherwise.
func (o *Dbv0037TresInfo) GetTres() [][]map[string]interface{} {
	if o == nil || o.Tres == nil {
		var ret [][]map[string]interface{}
		return ret
	}
	return *o.Tres
}

// GetTresOk returns a tuple with the Tres field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0037TresInfo) GetTresOk() (*[][]map[string]interface{}, bool) {
	if o == nil || o.Tres == nil {
		return nil, false
	}
	return o.Tres, true
}

// HasTres returns a boolean if a field has been set.
func (o *Dbv0037TresInfo) HasTres() bool {
	if o != nil && o.Tres != nil {
		return true
	}

	return false
}

// SetTres gets a reference to the given [][]map[string]interface{} and assigns it to the Tres field.
func (o *Dbv0037TresInfo) SetTres(v [][]map[string]interface{}) {
	o.Tres = &v
}

func (o Dbv0037TresInfo) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Errors != nil {
		toSerialize["errors"] = o.Errors
	}
	if o.Tres != nil {
		toSerialize["tres"] = o.Tres
	}
	return json.Marshal(toSerialize)
}

type NullableDbv0037TresInfo struct {
	value *Dbv0037TresInfo
	isSet bool
}

func (v NullableDbv0037TresInfo) Get() *Dbv0037TresInfo {
	return v.value
}

func (v *NullableDbv0037TresInfo) Set(val *Dbv0037TresInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableDbv0037TresInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableDbv0037TresInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDbv0037TresInfo(val *Dbv0037TresInfo) *NullableDbv0037TresInfo {
	return &NullableDbv0037TresInfo{value: val, isSet: true}
}

func (v NullableDbv0037TresInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDbv0037TresInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


