/*
 * Slurm Rest API
 *
 * API to access and control Slurm DB.
 *
 * API version: dbv0.0.37
 * Contact: sales@schedmd.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmdbrest

import (
	"encoding/json"
)

// Dbv0037ClusterInfoAssociations Information about associations
type Dbv0037ClusterInfoAssociations struct {
	Root *Dbv0037AssociationShortInfo `json:"root,omitempty"`
}

// NewDbv0037ClusterInfoAssociations instantiates a new Dbv0037ClusterInfoAssociations object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDbv0037ClusterInfoAssociations() *Dbv0037ClusterInfoAssociations {
	this := Dbv0037ClusterInfoAssociations{}
	return &this
}

// NewDbv0037ClusterInfoAssociationsWithDefaults instantiates a new Dbv0037ClusterInfoAssociations object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDbv0037ClusterInfoAssociationsWithDefaults() *Dbv0037ClusterInfoAssociations {
	this := Dbv0037ClusterInfoAssociations{}
	return &this
}

// GetRoot returns the Root field value if set, zero value otherwise.
func (o *Dbv0037ClusterInfoAssociations) GetRoot() Dbv0037AssociationShortInfo {
	if o == nil || o.Root == nil {
		var ret Dbv0037AssociationShortInfo
		return ret
	}
	return *o.Root
}

// GetRootOk returns a tuple with the Root field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0037ClusterInfoAssociations) GetRootOk() (*Dbv0037AssociationShortInfo, bool) {
	if o == nil || o.Root == nil {
		return nil, false
	}
	return o.Root, true
}

// HasRoot returns a boolean if a field has been set.
func (o *Dbv0037ClusterInfoAssociations) HasRoot() bool {
	if o != nil && o.Root != nil {
		return true
	}

	return false
}

// SetRoot gets a reference to the given Dbv0037AssociationShortInfo and assigns it to the Root field.
func (o *Dbv0037ClusterInfoAssociations) SetRoot(v Dbv0037AssociationShortInfo) {
	o.Root = &v
}

func (o Dbv0037ClusterInfoAssociations) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Root != nil {
		toSerialize["root"] = o.Root
	}
	return json.Marshal(toSerialize)
}

type NullableDbv0037ClusterInfoAssociations struct {
	value *Dbv0037ClusterInfoAssociations
	isSet bool
}

func (v NullableDbv0037ClusterInfoAssociations) Get() *Dbv0037ClusterInfoAssociations {
	return v.value
}

func (v *NullableDbv0037ClusterInfoAssociations) Set(val *Dbv0037ClusterInfoAssociations) {
	v.value = val
	v.isSet = true
}

func (v NullableDbv0037ClusterInfoAssociations) IsSet() bool {
	return v.isSet
}

func (v *NullableDbv0037ClusterInfoAssociations) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDbv0037ClusterInfoAssociations(val *Dbv0037ClusterInfoAssociations) *NullableDbv0037ClusterInfoAssociations {
	return &NullableDbv0037ClusterInfoAssociations{value: val, isSet: true}
}

func (v NullableDbv0037ClusterInfoAssociations) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDbv0037ClusterInfoAssociations) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


