/*
 * Slurm Rest API
 *
 * API to access and control Slurm DB.
 *
 * API version: dbv0.0.37
 * Contact: sales@schedmd.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmdbrest

import (
	"encoding/json"
)

// Dbv0037JobComment Job comments by type
type Dbv0037JobComment struct {
	// Administrator set comment
	Administrator *string `json:"administrator,omitempty"`
	// Job comment
	Job *string `json:"job,omitempty"`
	// System set comment
	System *string `json:"system,omitempty"`
}

// NewDbv0037JobComment instantiates a new Dbv0037JobComment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDbv0037JobComment() *Dbv0037JobComment {
	this := Dbv0037JobComment{}
	return &this
}

// NewDbv0037JobCommentWithDefaults instantiates a new Dbv0037JobComment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDbv0037JobCommentWithDefaults() *Dbv0037JobComment {
	this := Dbv0037JobComment{}
	return &this
}

// GetAdministrator returns the Administrator field value if set, zero value otherwise.
func (o *Dbv0037JobComment) GetAdministrator() string {
	if o == nil || o.Administrator == nil {
		var ret string
		return ret
	}
	return *o.Administrator
}

// GetAdministratorOk returns a tuple with the Administrator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0037JobComment) GetAdministratorOk() (*string, bool) {
	if o == nil || o.Administrator == nil {
		return nil, false
	}
	return o.Administrator, true
}

// HasAdministrator returns a boolean if a field has been set.
func (o *Dbv0037JobComment) HasAdministrator() bool {
	if o != nil && o.Administrator != nil {
		return true
	}

	return false
}

// SetAdministrator gets a reference to the given string and assigns it to the Administrator field.
func (o *Dbv0037JobComment) SetAdministrator(v string) {
	o.Administrator = &v
}

// GetJob returns the Job field value if set, zero value otherwise.
func (o *Dbv0037JobComment) GetJob() string {
	if o == nil || o.Job == nil {
		var ret string
		return ret
	}
	return *o.Job
}

// GetJobOk returns a tuple with the Job field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0037JobComment) GetJobOk() (*string, bool) {
	if o == nil || o.Job == nil {
		return nil, false
	}
	return o.Job, true
}

// HasJob returns a boolean if a field has been set.
func (o *Dbv0037JobComment) HasJob() bool {
	if o != nil && o.Job != nil {
		return true
	}

	return false
}

// SetJob gets a reference to the given string and assigns it to the Job field.
func (o *Dbv0037JobComment) SetJob(v string) {
	o.Job = &v
}

// GetSystem returns the System field value if set, zero value otherwise.
func (o *Dbv0037JobComment) GetSystem() string {
	if o == nil || o.System == nil {
		var ret string
		return ret
	}
	return *o.System
}

// GetSystemOk returns a tuple with the System field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0037JobComment) GetSystemOk() (*string, bool) {
	if o == nil || o.System == nil {
		return nil, false
	}
	return o.System, true
}

// HasSystem returns a boolean if a field has been set.
func (o *Dbv0037JobComment) HasSystem() bool {
	if o != nil && o.System != nil {
		return true
	}

	return false
}

// SetSystem gets a reference to the given string and assigns it to the System field.
func (o *Dbv0037JobComment) SetSystem(v string) {
	o.System = &v
}

func (o Dbv0037JobComment) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Administrator != nil {
		toSerialize["administrator"] = o.Administrator
	}
	if o.Job != nil {
		toSerialize["job"] = o.Job
	}
	if o.System != nil {
		toSerialize["system"] = o.System
	}
	return json.Marshal(toSerialize)
}

type NullableDbv0037JobComment struct {
	value *Dbv0037JobComment
	isSet bool
}

func (v NullableDbv0037JobComment) Get() *Dbv0037JobComment {
	return v.value
}

func (v *NullableDbv0037JobComment) Set(val *Dbv0037JobComment) {
	v.value = val
	v.isSet = true
}

func (v NullableDbv0037JobComment) IsSet() bool {
	return v.isSet
}

func (v *NullableDbv0037JobComment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDbv0037JobComment(val *Dbv0037JobComment) *NullableDbv0037JobComment {
	return &NullableDbv0037JobComment{value: val, isSet: true}
}

func (v NullableDbv0037JobComment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDbv0037JobComment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


