/*
 * Slurm Rest API
 *
 * API to access and control Slurm DB.
 *
 * API version: dbv0.0.37
 * Contact: sales@schedmd.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmdbrest

import (
	"encoding/json"
)

// Dbv0037DiagStatisticsUsers Statistics by user RPCs
type Dbv0037DiagStatisticsUsers struct {
	// User name
	User *string `json:"user,omitempty"`
	// Number of RPCs
	Count *int32 `json:"count,omitempty"`
	Time *Dbv0037DiagStatisticsTime1 `json:"time,omitempty"`
}

// NewDbv0037DiagStatisticsUsers instantiates a new Dbv0037DiagStatisticsUsers object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDbv0037DiagStatisticsUsers() *Dbv0037DiagStatisticsUsers {
	this := Dbv0037DiagStatisticsUsers{}
	return &this
}

// NewDbv0037DiagStatisticsUsersWithDefaults instantiates a new Dbv0037DiagStatisticsUsers object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDbv0037DiagStatisticsUsersWithDefaults() *Dbv0037DiagStatisticsUsers {
	this := Dbv0037DiagStatisticsUsers{}
	return &this
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *Dbv0037DiagStatisticsUsers) GetUser() string {
	if o == nil || o.User == nil {
		var ret string
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0037DiagStatisticsUsers) GetUserOk() (*string, bool) {
	if o == nil || o.User == nil {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *Dbv0037DiagStatisticsUsers) HasUser() bool {
	if o != nil && o.User != nil {
		return true
	}

	return false
}

// SetUser gets a reference to the given string and assigns it to the User field.
func (o *Dbv0037DiagStatisticsUsers) SetUser(v string) {
	o.User = &v
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *Dbv0037DiagStatisticsUsers) GetCount() int32 {
	if o == nil || o.Count == nil {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0037DiagStatisticsUsers) GetCountOk() (*int32, bool) {
	if o == nil || o.Count == nil {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *Dbv0037DiagStatisticsUsers) HasCount() bool {
	if o != nil && o.Count != nil {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *Dbv0037DiagStatisticsUsers) SetCount(v int32) {
	o.Count = &v
}

// GetTime returns the Time field value if set, zero value otherwise.
func (o *Dbv0037DiagStatisticsUsers) GetTime() Dbv0037DiagStatisticsTime1 {
	if o == nil || o.Time == nil {
		var ret Dbv0037DiagStatisticsTime1
		return ret
	}
	return *o.Time
}

// GetTimeOk returns a tuple with the Time field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0037DiagStatisticsUsers) GetTimeOk() (*Dbv0037DiagStatisticsTime1, bool) {
	if o == nil || o.Time == nil {
		return nil, false
	}
	return o.Time, true
}

// HasTime returns a boolean if a field has been set.
func (o *Dbv0037DiagStatisticsUsers) HasTime() bool {
	if o != nil && o.Time != nil {
		return true
	}

	return false
}

// SetTime gets a reference to the given Dbv0037DiagStatisticsTime1 and assigns it to the Time field.
func (o *Dbv0037DiagStatisticsUsers) SetTime(v Dbv0037DiagStatisticsTime1) {
	o.Time = &v
}

func (o Dbv0037DiagStatisticsUsers) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.User != nil {
		toSerialize["user"] = o.User
	}
	if o.Count != nil {
		toSerialize["count"] = o.Count
	}
	if o.Time != nil {
		toSerialize["time"] = o.Time
	}
	return json.Marshal(toSerialize)
}

type NullableDbv0037DiagStatisticsUsers struct {
	value *Dbv0037DiagStatisticsUsers
	isSet bool
}

func (v NullableDbv0037DiagStatisticsUsers) Get() *Dbv0037DiagStatisticsUsers {
	return v.value
}

func (v *NullableDbv0037DiagStatisticsUsers) Set(val *Dbv0037DiagStatisticsUsers) {
	v.value = val
	v.isSet = true
}

func (v NullableDbv0037DiagStatisticsUsers) IsSet() bool {
	return v.isSet
}

func (v *NullableDbv0037DiagStatisticsUsers) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDbv0037DiagStatisticsUsers(val *Dbv0037DiagStatisticsUsers) *NullableDbv0037DiagStatisticsUsers {
	return &NullableDbv0037DiagStatisticsUsers{value: val, isSet: true}
}

func (v NullableDbv0037DiagStatisticsUsers) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDbv0037DiagStatisticsUsers) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


