/*
 * Slurm Rest API
 *
 * API to access and control Slurm DB.
 *
 * API version: dbv0.0.37
 * Contact: sales@schedmd.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmdbrest

import (
	"encoding/json"
)

// Dbv0037DiagUsers Statistics by user RPCs
type Dbv0037DiagUsers struct {
	// User name
	User *string `json:"user,omitempty"`
	// Number of RPCs
	Count *int32 `json:"count,omitempty"`
	Time *Dbv0037DiagTime1 `json:"time,omitempty"`
}

// NewDbv0037DiagUsers instantiates a new Dbv0037DiagUsers object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDbv0037DiagUsers() *Dbv0037DiagUsers {
	this := Dbv0037DiagUsers{}
	return &this
}

// NewDbv0037DiagUsersWithDefaults instantiates a new Dbv0037DiagUsers object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDbv0037DiagUsersWithDefaults() *Dbv0037DiagUsers {
	this := Dbv0037DiagUsers{}
	return &this
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *Dbv0037DiagUsers) GetUser() string {
	if o == nil || o.User == nil {
		var ret string
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0037DiagUsers) GetUserOk() (*string, bool) {
	if o == nil || o.User == nil {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *Dbv0037DiagUsers) HasUser() bool {
	if o != nil && o.User != nil {
		return true
	}

	return false
}

// SetUser gets a reference to the given string and assigns it to the User field.
func (o *Dbv0037DiagUsers) SetUser(v string) {
	o.User = &v
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *Dbv0037DiagUsers) GetCount() int32 {
	if o == nil || o.Count == nil {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0037DiagUsers) GetCountOk() (*int32, bool) {
	if o == nil || o.Count == nil {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *Dbv0037DiagUsers) HasCount() bool {
	if o != nil && o.Count != nil {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *Dbv0037DiagUsers) SetCount(v int32) {
	o.Count = &v
}

// GetTime returns the Time field value if set, zero value otherwise.
func (o *Dbv0037DiagUsers) GetTime() Dbv0037DiagTime1 {
	if o == nil || o.Time == nil {
		var ret Dbv0037DiagTime1
		return ret
	}
	return *o.Time
}

// GetTimeOk returns a tuple with the Time field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0037DiagUsers) GetTimeOk() (*Dbv0037DiagTime1, bool) {
	if o == nil || o.Time == nil {
		return nil, false
	}
	return o.Time, true
}

// HasTime returns a boolean if a field has been set.
func (o *Dbv0037DiagUsers) HasTime() bool {
	if o != nil && o.Time != nil {
		return true
	}

	return false
}

// SetTime gets a reference to the given Dbv0037DiagTime1 and assigns it to the Time field.
func (o *Dbv0037DiagUsers) SetTime(v Dbv0037DiagTime1) {
	o.Time = &v
}

func (o Dbv0037DiagUsers) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.User != nil {
		toSerialize["user"] = o.User
	}
	if o.Count != nil {
		toSerialize["count"] = o.Count
	}
	if o.Time != nil {
		toSerialize["time"] = o.Time
	}
	return json.Marshal(toSerialize)
}

type NullableDbv0037DiagUsers struct {
	value *Dbv0037DiagUsers
	isSet bool
}

func (v NullableDbv0037DiagUsers) Get() *Dbv0037DiagUsers {
	return v.value
}

func (v *NullableDbv0037DiagUsers) Set(val *Dbv0037DiagUsers) {
	v.value = val
	v.isSet = true
}

func (v NullableDbv0037DiagUsers) IsSet() bool {
	return v.isSet
}

func (v *NullableDbv0037DiagUsers) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDbv0037DiagUsers(val *Dbv0037DiagUsers) *NullableDbv0037DiagUsers {
	return &NullableDbv0037DiagUsers{value: val, isSet: true}
}

func (v NullableDbv0037DiagUsers) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDbv0037DiagUsers) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


