/*
 * Slurm Rest API
 *
 * API to access and control Slurm DB.
 *
 * API version: dbv0.0.37
 * Contact: sales@schedmd.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmdbrest

import (
	"encoding/json"
)

// Dbv0037JobArray Array properties (optional)
type Dbv0037JobArray struct {
	// Job id of array
	JobId *int32 `json:"job_id,omitempty"`
	Limits *Dbv0037JobArrayLimits `json:"limits,omitempty"`
	// Array task
	Task *string `json:"task,omitempty"`
	// Array task id
	TaskId *int32 `json:"task_id,omitempty"`
}

// NewDbv0037JobArray instantiates a new Dbv0037JobArray object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDbv0037JobArray() *Dbv0037JobArray {
	this := Dbv0037JobArray{}
	return &this
}

// NewDbv0037JobArrayWithDefaults instantiates a new Dbv0037JobArray object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDbv0037JobArrayWithDefaults() *Dbv0037JobArray {
	this := Dbv0037JobArray{}
	return &this
}

// GetJobId returns the JobId field value if set, zero value otherwise.
func (o *Dbv0037JobArray) GetJobId() int32 {
	if o == nil || o.JobId == nil {
		var ret int32
		return ret
	}
	return *o.JobId
}

// GetJobIdOk returns a tuple with the JobId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0037JobArray) GetJobIdOk() (*int32, bool) {
	if o == nil || o.JobId == nil {
		return nil, false
	}
	return o.JobId, true
}

// HasJobId returns a boolean if a field has been set.
func (o *Dbv0037JobArray) HasJobId() bool {
	if o != nil && o.JobId != nil {
		return true
	}

	return false
}

// SetJobId gets a reference to the given int32 and assigns it to the JobId field.
func (o *Dbv0037JobArray) SetJobId(v int32) {
	o.JobId = &v
}

// GetLimits returns the Limits field value if set, zero value otherwise.
func (o *Dbv0037JobArray) GetLimits() Dbv0037JobArrayLimits {
	if o == nil || o.Limits == nil {
		var ret Dbv0037JobArrayLimits
		return ret
	}
	return *o.Limits
}

// GetLimitsOk returns a tuple with the Limits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0037JobArray) GetLimitsOk() (*Dbv0037JobArrayLimits, bool) {
	if o == nil || o.Limits == nil {
		return nil, false
	}
	return o.Limits, true
}

// HasLimits returns a boolean if a field has been set.
func (o *Dbv0037JobArray) HasLimits() bool {
	if o != nil && o.Limits != nil {
		return true
	}

	return false
}

// SetLimits gets a reference to the given Dbv0037JobArrayLimits and assigns it to the Limits field.
func (o *Dbv0037JobArray) SetLimits(v Dbv0037JobArrayLimits) {
	o.Limits = &v
}

// GetTask returns the Task field value if set, zero value otherwise.
func (o *Dbv0037JobArray) GetTask() string {
	if o == nil || o.Task == nil {
		var ret string
		return ret
	}
	return *o.Task
}

// GetTaskOk returns a tuple with the Task field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0037JobArray) GetTaskOk() (*string, bool) {
	if o == nil || o.Task == nil {
		return nil, false
	}
	return o.Task, true
}

// HasTask returns a boolean if a field has been set.
func (o *Dbv0037JobArray) HasTask() bool {
	if o != nil && o.Task != nil {
		return true
	}

	return false
}

// SetTask gets a reference to the given string and assigns it to the Task field.
func (o *Dbv0037JobArray) SetTask(v string) {
	o.Task = &v
}

// GetTaskId returns the TaskId field value if set, zero value otherwise.
func (o *Dbv0037JobArray) GetTaskId() int32 {
	if o == nil || o.TaskId == nil {
		var ret int32
		return ret
	}
	return *o.TaskId
}

// GetTaskIdOk returns a tuple with the TaskId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0037JobArray) GetTaskIdOk() (*int32, bool) {
	if o == nil || o.TaskId == nil {
		return nil, false
	}
	return o.TaskId, true
}

// HasTaskId returns a boolean if a field has been set.
func (o *Dbv0037JobArray) HasTaskId() bool {
	if o != nil && o.TaskId != nil {
		return true
	}

	return false
}

// SetTaskId gets a reference to the given int32 and assigns it to the TaskId field.
func (o *Dbv0037JobArray) SetTaskId(v int32) {
	o.TaskId = &v
}

func (o Dbv0037JobArray) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.JobId != nil {
		toSerialize["job_id"] = o.JobId
	}
	if o.Limits != nil {
		toSerialize["limits"] = o.Limits
	}
	if o.Task != nil {
		toSerialize["task"] = o.Task
	}
	if o.TaskId != nil {
		toSerialize["task_id"] = o.TaskId
	}
	return json.Marshal(toSerialize)
}

type NullableDbv0037JobArray struct {
	value *Dbv0037JobArray
	isSet bool
}

func (v NullableDbv0037JobArray) Get() *Dbv0037JobArray {
	return v.value
}

func (v *NullableDbv0037JobArray) Set(val *Dbv0037JobArray) {
	v.value = val
	v.isSet = true
}

func (v NullableDbv0037JobArray) IsSet() bool {
	return v.isSet
}

func (v *NullableDbv0037JobArray) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDbv0037JobArray(val *Dbv0037JobArray) *NullableDbv0037JobArray {
	return &NullableDbv0037JobArray{value: val, isSet: true}
}

func (v NullableDbv0037JobArray) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDbv0037JobArray) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


