/*
 * Slurm Rest API
 *
 * API to access and control Slurm DB.
 *
 * API version: dbv0.0.37
 * Contact: sales@schedmd.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmdbrest

import (
	"encoding/json"
)

// Dbv0037JobStepStepTask Task properties
type Dbv0037JobStepStepTask struct {
	// Task distribution type
	Distribution *string `json:"distribution,omitempty"`
}

// NewDbv0037JobStepStepTask instantiates a new Dbv0037JobStepStepTask object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDbv0037JobStepStepTask() *Dbv0037JobStepStepTask {
	this := Dbv0037JobStepStepTask{}
	return &this
}

// NewDbv0037JobStepStepTaskWithDefaults instantiates a new Dbv0037JobStepStepTask object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDbv0037JobStepStepTaskWithDefaults() *Dbv0037JobStepStepTask {
	this := Dbv0037JobStepStepTask{}
	return &this
}

// GetDistribution returns the Distribution field value if set, zero value otherwise.
func (o *Dbv0037JobStepStepTask) GetDistribution() string {
	if o == nil || o.Distribution == nil {
		var ret string
		return ret
	}
	return *o.Distribution
}

// GetDistributionOk returns a tuple with the Distribution field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0037JobStepStepTask) GetDistributionOk() (*string, bool) {
	if o == nil || o.Distribution == nil {
		return nil, false
	}
	return o.Distribution, true
}

// HasDistribution returns a boolean if a field has been set.
func (o *Dbv0037JobStepStepTask) HasDistribution() bool {
	if o != nil && o.Distribution != nil {
		return true
	}

	return false
}

// SetDistribution gets a reference to the given string and assigns it to the Distribution field.
func (o *Dbv0037JobStepStepTask) SetDistribution(v string) {
	o.Distribution = &v
}

func (o Dbv0037JobStepStepTask) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Distribution != nil {
		toSerialize["distribution"] = o.Distribution
	}
	return json.Marshal(toSerialize)
}

type NullableDbv0037JobStepStepTask struct {
	value *Dbv0037JobStepStepTask
	isSet bool
}

func (v NullableDbv0037JobStepStepTask) Get() *Dbv0037JobStepStepTask {
	return v.value
}

func (v *NullableDbv0037JobStepStepTask) Set(val *Dbv0037JobStepStepTask) {
	v.value = val
	v.isSet = true
}

func (v NullableDbv0037JobStepStepTask) IsSet() bool {
	return v.isSet
}

func (v *NullableDbv0037JobStepStepTask) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDbv0037JobStepStepTask(val *Dbv0037JobStepStepTask) *NullableDbv0037JobStepStepTask {
	return &NullableDbv0037JobStepStepTask{value: val, isSet: true}
}

func (v NullableDbv0037JobStepStepTask) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDbv0037JobStepStepTask) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


