/*
 * Slurm Rest API
 *
 * API to access and control Slurm DB.
 *
 * API version: dbv0.0.37
 * Contact: sales@schedmd.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmdbrest

import (
	"encoding/json"
)

// Dbv0037Association Association description
type Dbv0037Association struct {
	// Assigned account
	Account *string `json:"account,omitempty"`
	// Assigned cluster
	Cluster *string `json:"cluster,omitempty"`
	Default *Dbv0037AssociationDefault `json:"default,omitempty"`
	// List of properties of association
	Flags *[]string `json:"flags,omitempty"`
	Max *Dbv0037AssociationMax `json:"max,omitempty"`
	Min *Dbv0037AssociationMin `json:"min,omitempty"`
	// Parent account name
	ParentAccount *string `json:"parent_account,omitempty"`
	// Assigned partition
	Partition *string `json:"partition,omitempty"`
	// Assigned priority
	Priority *int32 `json:"priority,omitempty"`
	// Assigned QOS
	Qos *[]string `json:"qos,omitempty"`
	// Raw fairshare shares
	SharesRaw *int32 `json:"shares_raw,omitempty"`
	Usage *Dbv0037AssociationUsage `json:"usage,omitempty"`
	// Assigned user
	User *string `json:"user,omitempty"`
}

// NewDbv0037Association instantiates a new Dbv0037Association object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDbv0037Association() *Dbv0037Association {
	this := Dbv0037Association{}
	return &this
}

// NewDbv0037AssociationWithDefaults instantiates a new Dbv0037Association object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDbv0037AssociationWithDefaults() *Dbv0037Association {
	this := Dbv0037Association{}
	return &this
}

// GetAccount returns the Account field value if set, zero value otherwise.
func (o *Dbv0037Association) GetAccount() string {
	if o == nil || o.Account == nil {
		var ret string
		return ret
	}
	return *o.Account
}

// GetAccountOk returns a tuple with the Account field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0037Association) GetAccountOk() (*string, bool) {
	if o == nil || o.Account == nil {
		return nil, false
	}
	return o.Account, true
}

// HasAccount returns a boolean if a field has been set.
func (o *Dbv0037Association) HasAccount() bool {
	if o != nil && o.Account != nil {
		return true
	}

	return false
}

// SetAccount gets a reference to the given string and assigns it to the Account field.
func (o *Dbv0037Association) SetAccount(v string) {
	o.Account = &v
}

// GetCluster returns the Cluster field value if set, zero value otherwise.
func (o *Dbv0037Association) GetCluster() string {
	if o == nil || o.Cluster == nil {
		var ret string
		return ret
	}
	return *o.Cluster
}

// GetClusterOk returns a tuple with the Cluster field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0037Association) GetClusterOk() (*string, bool) {
	if o == nil || o.Cluster == nil {
		return nil, false
	}
	return o.Cluster, true
}

// HasCluster returns a boolean if a field has been set.
func (o *Dbv0037Association) HasCluster() bool {
	if o != nil && o.Cluster != nil {
		return true
	}

	return false
}

// SetCluster gets a reference to the given string and assigns it to the Cluster field.
func (o *Dbv0037Association) SetCluster(v string) {
	o.Cluster = &v
}

// GetDefault returns the Default field value if set, zero value otherwise.
func (o *Dbv0037Association) GetDefault() Dbv0037AssociationDefault {
	if o == nil || o.Default == nil {
		var ret Dbv0037AssociationDefault
		return ret
	}
	return *o.Default
}

// GetDefaultOk returns a tuple with the Default field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0037Association) GetDefaultOk() (*Dbv0037AssociationDefault, bool) {
	if o == nil || o.Default == nil {
		return nil, false
	}
	return o.Default, true
}

// HasDefault returns a boolean if a field has been set.
func (o *Dbv0037Association) HasDefault() bool {
	if o != nil && o.Default != nil {
		return true
	}

	return false
}

// SetDefault gets a reference to the given Dbv0037AssociationDefault and assigns it to the Default field.
func (o *Dbv0037Association) SetDefault(v Dbv0037AssociationDefault) {
	o.Default = &v
}

// GetFlags returns the Flags field value if set, zero value otherwise.
func (o *Dbv0037Association) GetFlags() []string {
	if o == nil || o.Flags == nil {
		var ret []string
		return ret
	}
	return *o.Flags
}

// GetFlagsOk returns a tuple with the Flags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0037Association) GetFlagsOk() (*[]string, bool) {
	if o == nil || o.Flags == nil {
		return nil, false
	}
	return o.Flags, true
}

// HasFlags returns a boolean if a field has been set.
func (o *Dbv0037Association) HasFlags() bool {
	if o != nil && o.Flags != nil {
		return true
	}

	return false
}

// SetFlags gets a reference to the given []string and assigns it to the Flags field.
func (o *Dbv0037Association) SetFlags(v []string) {
	o.Flags = &v
}

// GetMax returns the Max field value if set, zero value otherwise.
func (o *Dbv0037Association) GetMax() Dbv0037AssociationMax {
	if o == nil || o.Max == nil {
		var ret Dbv0037AssociationMax
		return ret
	}
	return *o.Max
}

// GetMaxOk returns a tuple with the Max field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0037Association) GetMaxOk() (*Dbv0037AssociationMax, bool) {
	if o == nil || o.Max == nil {
		return nil, false
	}
	return o.Max, true
}

// HasMax returns a boolean if a field has been set.
func (o *Dbv0037Association) HasMax() bool {
	if o != nil && o.Max != nil {
		return true
	}

	return false
}

// SetMax gets a reference to the given Dbv0037AssociationMax and assigns it to the Max field.
func (o *Dbv0037Association) SetMax(v Dbv0037AssociationMax) {
	o.Max = &v
}

// GetMin returns the Min field value if set, zero value otherwise.
func (o *Dbv0037Association) GetMin() Dbv0037AssociationMin {
	if o == nil || o.Min == nil {
		var ret Dbv0037AssociationMin
		return ret
	}
	return *o.Min
}

// GetMinOk returns a tuple with the Min field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0037Association) GetMinOk() (*Dbv0037AssociationMin, bool) {
	if o == nil || o.Min == nil {
		return nil, false
	}
	return o.Min, true
}

// HasMin returns a boolean if a field has been set.
func (o *Dbv0037Association) HasMin() bool {
	if o != nil && o.Min != nil {
		return true
	}

	return false
}

// SetMin gets a reference to the given Dbv0037AssociationMin and assigns it to the Min field.
func (o *Dbv0037Association) SetMin(v Dbv0037AssociationMin) {
	o.Min = &v
}

// GetParentAccount returns the ParentAccount field value if set, zero value otherwise.
func (o *Dbv0037Association) GetParentAccount() string {
	if o == nil || o.ParentAccount == nil {
		var ret string
		return ret
	}
	return *o.ParentAccount
}

// GetParentAccountOk returns a tuple with the ParentAccount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0037Association) GetParentAccountOk() (*string, bool) {
	if o == nil || o.ParentAccount == nil {
		return nil, false
	}
	return o.ParentAccount, true
}

// HasParentAccount returns a boolean if a field has been set.
func (o *Dbv0037Association) HasParentAccount() bool {
	if o != nil && o.ParentAccount != nil {
		return true
	}

	return false
}

// SetParentAccount gets a reference to the given string and assigns it to the ParentAccount field.
func (o *Dbv0037Association) SetParentAccount(v string) {
	o.ParentAccount = &v
}

// GetPartition returns the Partition field value if set, zero value otherwise.
func (o *Dbv0037Association) GetPartition() string {
	if o == nil || o.Partition == nil {
		var ret string
		return ret
	}
	return *o.Partition
}

// GetPartitionOk returns a tuple with the Partition field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0037Association) GetPartitionOk() (*string, bool) {
	if o == nil || o.Partition == nil {
		return nil, false
	}
	return o.Partition, true
}

// HasPartition returns a boolean if a field has been set.
func (o *Dbv0037Association) HasPartition() bool {
	if o != nil && o.Partition != nil {
		return true
	}

	return false
}

// SetPartition gets a reference to the given string and assigns it to the Partition field.
func (o *Dbv0037Association) SetPartition(v string) {
	o.Partition = &v
}

// GetPriority returns the Priority field value if set, zero value otherwise.
func (o *Dbv0037Association) GetPriority() int32 {
	if o == nil || o.Priority == nil {
		var ret int32
		return ret
	}
	return *o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0037Association) GetPriorityOk() (*int32, bool) {
	if o == nil || o.Priority == nil {
		return nil, false
	}
	return o.Priority, true
}

// HasPriority returns a boolean if a field has been set.
func (o *Dbv0037Association) HasPriority() bool {
	if o != nil && o.Priority != nil {
		return true
	}

	return false
}

// SetPriority gets a reference to the given int32 and assigns it to the Priority field.
func (o *Dbv0037Association) SetPriority(v int32) {
	o.Priority = &v
}

// GetQos returns the Qos field value if set, zero value otherwise.
func (o *Dbv0037Association) GetQos() []string {
	if o == nil || o.Qos == nil {
		var ret []string
		return ret
	}
	return *o.Qos
}

// GetQosOk returns a tuple with the Qos field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0037Association) GetQosOk() (*[]string, bool) {
	if o == nil || o.Qos == nil {
		return nil, false
	}
	return o.Qos, true
}

// HasQos returns a boolean if a field has been set.
func (o *Dbv0037Association) HasQos() bool {
	if o != nil && o.Qos != nil {
		return true
	}

	return false
}

// SetQos gets a reference to the given []string and assigns it to the Qos field.
func (o *Dbv0037Association) SetQos(v []string) {
	o.Qos = &v
}

// GetSharesRaw returns the SharesRaw field value if set, zero value otherwise.
func (o *Dbv0037Association) GetSharesRaw() int32 {
	if o == nil || o.SharesRaw == nil {
		var ret int32
		return ret
	}
	return *o.SharesRaw
}

// GetSharesRawOk returns a tuple with the SharesRaw field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0037Association) GetSharesRawOk() (*int32, bool) {
	if o == nil || o.SharesRaw == nil {
		return nil, false
	}
	return o.SharesRaw, true
}

// HasSharesRaw returns a boolean if a field has been set.
func (o *Dbv0037Association) HasSharesRaw() bool {
	if o != nil && o.SharesRaw != nil {
		return true
	}

	return false
}

// SetSharesRaw gets a reference to the given int32 and assigns it to the SharesRaw field.
func (o *Dbv0037Association) SetSharesRaw(v int32) {
	o.SharesRaw = &v
}

// GetUsage returns the Usage field value if set, zero value otherwise.
func (o *Dbv0037Association) GetUsage() Dbv0037AssociationUsage {
	if o == nil || o.Usage == nil {
		var ret Dbv0037AssociationUsage
		return ret
	}
	return *o.Usage
}

// GetUsageOk returns a tuple with the Usage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0037Association) GetUsageOk() (*Dbv0037AssociationUsage, bool) {
	if o == nil || o.Usage == nil {
		return nil, false
	}
	return o.Usage, true
}

// HasUsage returns a boolean if a field has been set.
func (o *Dbv0037Association) HasUsage() bool {
	if o != nil && o.Usage != nil {
		return true
	}

	return false
}

// SetUsage gets a reference to the given Dbv0037AssociationUsage and assigns it to the Usage field.
func (o *Dbv0037Association) SetUsage(v Dbv0037AssociationUsage) {
	o.Usage = &v
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *Dbv0037Association) GetUser() string {
	if o == nil || o.User == nil {
		var ret string
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0037Association) GetUserOk() (*string, bool) {
	if o == nil || o.User == nil {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *Dbv0037Association) HasUser() bool {
	if o != nil && o.User != nil {
		return true
	}

	return false
}

// SetUser gets a reference to the given string and assigns it to the User field.
func (o *Dbv0037Association) SetUser(v string) {
	o.User = &v
}

func (o Dbv0037Association) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Account != nil {
		toSerialize["account"] = o.Account
	}
	if o.Cluster != nil {
		toSerialize["cluster"] = o.Cluster
	}
	if o.Default != nil {
		toSerialize["default"] = o.Default
	}
	if o.Flags != nil {
		toSerialize["flags"] = o.Flags
	}
	if o.Max != nil {
		toSerialize["max"] = o.Max
	}
	if o.Min != nil {
		toSerialize["min"] = o.Min
	}
	if o.ParentAccount != nil {
		toSerialize["parent_account"] = o.ParentAccount
	}
	if o.Partition != nil {
		toSerialize["partition"] = o.Partition
	}
	if o.Priority != nil {
		toSerialize["priority"] = o.Priority
	}
	if o.Qos != nil {
		toSerialize["qos"] = o.Qos
	}
	if o.SharesRaw != nil {
		toSerialize["shares_raw"] = o.SharesRaw
	}
	if o.Usage != nil {
		toSerialize["usage"] = o.Usage
	}
	if o.User != nil {
		toSerialize["user"] = o.User
	}
	return json.Marshal(toSerialize)
}

type NullableDbv0037Association struct {
	value *Dbv0037Association
	isSet bool
}

func (v NullableDbv0037Association) Get() *Dbv0037Association {
	return v.value
}

func (v *NullableDbv0037Association) Set(val *Dbv0037Association) {
	v.value = val
	v.isSet = true
}

func (v NullableDbv0037Association) IsSet() bool {
	return v.isSet
}

func (v *NullableDbv0037Association) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDbv0037Association(val *Dbv0037Association) *NullableDbv0037Association {
	return &NullableDbv0037Association{value: val, isSet: true}
}

func (v NullableDbv0037Association) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDbv0037Association) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


