/*
 * Slurm Rest API
 *
 * API to access and control Slurm DB.
 *
 * API version: dbv0.0.37
 * Contact: sales@schedmd.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmdbrest

import (
	"encoding/json"
)

// Dbv0037QosLimitsMaxTresPer Max TRES per settings
type Dbv0037QosLimitsMaxTresPer struct {
	// TRES list of attributes
	Account *[]map[string]interface{} `json:"account,omitempty"`
	// TRES list of attributes
	Job *[]map[string]interface{} `json:"job,omitempty"`
	// TRES list of attributes
	Node *[]map[string]interface{} `json:"node,omitempty"`
	// TRES list of attributes
	User *[]map[string]interface{} `json:"user,omitempty"`
}

// NewDbv0037QosLimitsMaxTresPer instantiates a new Dbv0037QosLimitsMaxTresPer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDbv0037QosLimitsMaxTresPer() *Dbv0037QosLimitsMaxTresPer {
	this := Dbv0037QosLimitsMaxTresPer{}
	return &this
}

// NewDbv0037QosLimitsMaxTresPerWithDefaults instantiates a new Dbv0037QosLimitsMaxTresPer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDbv0037QosLimitsMaxTresPerWithDefaults() *Dbv0037QosLimitsMaxTresPer {
	this := Dbv0037QosLimitsMaxTresPer{}
	return &this
}

// GetAccount returns the Account field value if set, zero value otherwise.
func (o *Dbv0037QosLimitsMaxTresPer) GetAccount() []map[string]interface{} {
	if o == nil || o.Account == nil {
		var ret []map[string]interface{}
		return ret
	}
	return *o.Account
}

// GetAccountOk returns a tuple with the Account field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0037QosLimitsMaxTresPer) GetAccountOk() (*[]map[string]interface{}, bool) {
	if o == nil || o.Account == nil {
		return nil, false
	}
	return o.Account, true
}

// HasAccount returns a boolean if a field has been set.
func (o *Dbv0037QosLimitsMaxTresPer) HasAccount() bool {
	if o != nil && o.Account != nil {
		return true
	}

	return false
}

// SetAccount gets a reference to the given []map[string]interface{} and assigns it to the Account field.
func (o *Dbv0037QosLimitsMaxTresPer) SetAccount(v []map[string]interface{}) {
	o.Account = &v
}

// GetJob returns the Job field value if set, zero value otherwise.
func (o *Dbv0037QosLimitsMaxTresPer) GetJob() []map[string]interface{} {
	if o == nil || o.Job == nil {
		var ret []map[string]interface{}
		return ret
	}
	return *o.Job
}

// GetJobOk returns a tuple with the Job field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0037QosLimitsMaxTresPer) GetJobOk() (*[]map[string]interface{}, bool) {
	if o == nil || o.Job == nil {
		return nil, false
	}
	return o.Job, true
}

// HasJob returns a boolean if a field has been set.
func (o *Dbv0037QosLimitsMaxTresPer) HasJob() bool {
	if o != nil && o.Job != nil {
		return true
	}

	return false
}

// SetJob gets a reference to the given []map[string]interface{} and assigns it to the Job field.
func (o *Dbv0037QosLimitsMaxTresPer) SetJob(v []map[string]interface{}) {
	o.Job = &v
}

// GetNode returns the Node field value if set, zero value otherwise.
func (o *Dbv0037QosLimitsMaxTresPer) GetNode() []map[string]interface{} {
	if o == nil || o.Node == nil {
		var ret []map[string]interface{}
		return ret
	}
	return *o.Node
}

// GetNodeOk returns a tuple with the Node field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0037QosLimitsMaxTresPer) GetNodeOk() (*[]map[string]interface{}, bool) {
	if o == nil || o.Node == nil {
		return nil, false
	}
	return o.Node, true
}

// HasNode returns a boolean if a field has been set.
func (o *Dbv0037QosLimitsMaxTresPer) HasNode() bool {
	if o != nil && o.Node != nil {
		return true
	}

	return false
}

// SetNode gets a reference to the given []map[string]interface{} and assigns it to the Node field.
func (o *Dbv0037QosLimitsMaxTresPer) SetNode(v []map[string]interface{}) {
	o.Node = &v
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *Dbv0037QosLimitsMaxTresPer) GetUser() []map[string]interface{} {
	if o == nil || o.User == nil {
		var ret []map[string]interface{}
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0037QosLimitsMaxTresPer) GetUserOk() (*[]map[string]interface{}, bool) {
	if o == nil || o.User == nil {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *Dbv0037QosLimitsMaxTresPer) HasUser() bool {
	if o != nil && o.User != nil {
		return true
	}

	return false
}

// SetUser gets a reference to the given []map[string]interface{} and assigns it to the User field.
func (o *Dbv0037QosLimitsMaxTresPer) SetUser(v []map[string]interface{}) {
	o.User = &v
}

func (o Dbv0037QosLimitsMaxTresPer) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Account != nil {
		toSerialize["account"] = o.Account
	}
	if o.Job != nil {
		toSerialize["job"] = o.Job
	}
	if o.Node != nil {
		toSerialize["node"] = o.Node
	}
	if o.User != nil {
		toSerialize["user"] = o.User
	}
	return json.Marshal(toSerialize)
}

type NullableDbv0037QosLimitsMaxTresPer struct {
	value *Dbv0037QosLimitsMaxTresPer
	isSet bool
}

func (v NullableDbv0037QosLimitsMaxTresPer) Get() *Dbv0037QosLimitsMaxTresPer {
	return v.value
}

func (v *NullableDbv0037QosLimitsMaxTresPer) Set(val *Dbv0037QosLimitsMaxTresPer) {
	v.value = val
	v.isSet = true
}

func (v NullableDbv0037QosLimitsMaxTresPer) IsSet() bool {
	return v.isSet
}

func (v *NullableDbv0037QosLimitsMaxTresPer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDbv0037QosLimitsMaxTresPer(val *Dbv0037QosLimitsMaxTresPer) *NullableDbv0037QosLimitsMaxTresPer {
	return &NullableDbv0037QosLimitsMaxTresPer{value: val, isSet: true}
}

func (v NullableDbv0037QosLimitsMaxTresPer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDbv0037QosLimitsMaxTresPer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


