/*
 * Slurm Rest API
 *
 * API to access and control Slurm DB.
 *
 * API version: dbv0.0.37
 * Contact: sales@schedmd.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmdbrest

import (
	"encoding/json"
)

// Dbv0037DiagStatisticsRollups Rollup statistics
type Dbv0037DiagStatisticsRollups struct {
	// Type of rollup
	Type *string `json:"type,omitempty"`
	// Timestamp of last rollup
	LastRun *int32 `json:"last_run,omitempty"`
	// Timestamp of last cycle
	LastCycle *int32 `json:"last_cycle,omitempty"`
	// Max time of all cycles
	MaxCycle *int32 `json:"max_cycle,omitempty"`
	// Total time (s) spent doing rollup
	TotalTime *int32 `json:"total_time,omitempty"`
	// Average time (s) of cycle
	MeanCycles *int32 `json:"mean_cycles,omitempty"`
}

// NewDbv0037DiagStatisticsRollups instantiates a new Dbv0037DiagStatisticsRollups object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDbv0037DiagStatisticsRollups() *Dbv0037DiagStatisticsRollups {
	this := Dbv0037DiagStatisticsRollups{}
	return &this
}

// NewDbv0037DiagStatisticsRollupsWithDefaults instantiates a new Dbv0037DiagStatisticsRollups object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDbv0037DiagStatisticsRollupsWithDefaults() *Dbv0037DiagStatisticsRollups {
	this := Dbv0037DiagStatisticsRollups{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *Dbv0037DiagStatisticsRollups) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0037DiagStatisticsRollups) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *Dbv0037DiagStatisticsRollups) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *Dbv0037DiagStatisticsRollups) SetType(v string) {
	o.Type = &v
}

// GetLastRun returns the LastRun field value if set, zero value otherwise.
func (o *Dbv0037DiagStatisticsRollups) GetLastRun() int32 {
	if o == nil || o.LastRun == nil {
		var ret int32
		return ret
	}
	return *o.LastRun
}

// GetLastRunOk returns a tuple with the LastRun field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0037DiagStatisticsRollups) GetLastRunOk() (*int32, bool) {
	if o == nil || o.LastRun == nil {
		return nil, false
	}
	return o.LastRun, true
}

// HasLastRun returns a boolean if a field has been set.
func (o *Dbv0037DiagStatisticsRollups) HasLastRun() bool {
	if o != nil && o.LastRun != nil {
		return true
	}

	return false
}

// SetLastRun gets a reference to the given int32 and assigns it to the LastRun field.
func (o *Dbv0037DiagStatisticsRollups) SetLastRun(v int32) {
	o.LastRun = &v
}

// GetLastCycle returns the LastCycle field value if set, zero value otherwise.
func (o *Dbv0037DiagStatisticsRollups) GetLastCycle() int32 {
	if o == nil || o.LastCycle == nil {
		var ret int32
		return ret
	}
	return *o.LastCycle
}

// GetLastCycleOk returns a tuple with the LastCycle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0037DiagStatisticsRollups) GetLastCycleOk() (*int32, bool) {
	if o == nil || o.LastCycle == nil {
		return nil, false
	}
	return o.LastCycle, true
}

// HasLastCycle returns a boolean if a field has been set.
func (o *Dbv0037DiagStatisticsRollups) HasLastCycle() bool {
	if o != nil && o.LastCycle != nil {
		return true
	}

	return false
}

// SetLastCycle gets a reference to the given int32 and assigns it to the LastCycle field.
func (o *Dbv0037DiagStatisticsRollups) SetLastCycle(v int32) {
	o.LastCycle = &v
}

// GetMaxCycle returns the MaxCycle field value if set, zero value otherwise.
func (o *Dbv0037DiagStatisticsRollups) GetMaxCycle() int32 {
	if o == nil || o.MaxCycle == nil {
		var ret int32
		return ret
	}
	return *o.MaxCycle
}

// GetMaxCycleOk returns a tuple with the MaxCycle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0037DiagStatisticsRollups) GetMaxCycleOk() (*int32, bool) {
	if o == nil || o.MaxCycle == nil {
		return nil, false
	}
	return o.MaxCycle, true
}

// HasMaxCycle returns a boolean if a field has been set.
func (o *Dbv0037DiagStatisticsRollups) HasMaxCycle() bool {
	if o != nil && o.MaxCycle != nil {
		return true
	}

	return false
}

// SetMaxCycle gets a reference to the given int32 and assigns it to the MaxCycle field.
func (o *Dbv0037DiagStatisticsRollups) SetMaxCycle(v int32) {
	o.MaxCycle = &v
}

// GetTotalTime returns the TotalTime field value if set, zero value otherwise.
func (o *Dbv0037DiagStatisticsRollups) GetTotalTime() int32 {
	if o == nil || o.TotalTime == nil {
		var ret int32
		return ret
	}
	return *o.TotalTime
}

// GetTotalTimeOk returns a tuple with the TotalTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0037DiagStatisticsRollups) GetTotalTimeOk() (*int32, bool) {
	if o == nil || o.TotalTime == nil {
		return nil, false
	}
	return o.TotalTime, true
}

// HasTotalTime returns a boolean if a field has been set.
func (o *Dbv0037DiagStatisticsRollups) HasTotalTime() bool {
	if o != nil && o.TotalTime != nil {
		return true
	}

	return false
}

// SetTotalTime gets a reference to the given int32 and assigns it to the TotalTime field.
func (o *Dbv0037DiagStatisticsRollups) SetTotalTime(v int32) {
	o.TotalTime = &v
}

// GetMeanCycles returns the MeanCycles field value if set, zero value otherwise.
func (o *Dbv0037DiagStatisticsRollups) GetMeanCycles() int32 {
	if o == nil || o.MeanCycles == nil {
		var ret int32
		return ret
	}
	return *o.MeanCycles
}

// GetMeanCyclesOk returns a tuple with the MeanCycles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0037DiagStatisticsRollups) GetMeanCyclesOk() (*int32, bool) {
	if o == nil || o.MeanCycles == nil {
		return nil, false
	}
	return o.MeanCycles, true
}

// HasMeanCycles returns a boolean if a field has been set.
func (o *Dbv0037DiagStatisticsRollups) HasMeanCycles() bool {
	if o != nil && o.MeanCycles != nil {
		return true
	}

	return false
}

// SetMeanCycles gets a reference to the given int32 and assigns it to the MeanCycles field.
func (o *Dbv0037DiagStatisticsRollups) SetMeanCycles(v int32) {
	o.MeanCycles = &v
}

func (o Dbv0037DiagStatisticsRollups) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.LastRun != nil {
		toSerialize["last_run"] = o.LastRun
	}
	if o.LastCycle != nil {
		toSerialize["last_cycle"] = o.LastCycle
	}
	if o.MaxCycle != nil {
		toSerialize["max_cycle"] = o.MaxCycle
	}
	if o.TotalTime != nil {
		toSerialize["total_time"] = o.TotalTime
	}
	if o.MeanCycles != nil {
		toSerialize["mean_cycles"] = o.MeanCycles
	}
	return json.Marshal(toSerialize)
}

type NullableDbv0037DiagStatisticsRollups struct {
	value *Dbv0037DiagStatisticsRollups
	isSet bool
}

func (v NullableDbv0037DiagStatisticsRollups) Get() *Dbv0037DiagStatisticsRollups {
	return v.value
}

func (v *NullableDbv0037DiagStatisticsRollups) Set(val *Dbv0037DiagStatisticsRollups) {
	v.value = val
	v.isSet = true
}

func (v NullableDbv0037DiagStatisticsRollups) IsSet() bool {
	return v.isSet
}

func (v *NullableDbv0037DiagStatisticsRollups) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDbv0037DiagStatisticsRollups(val *Dbv0037DiagStatisticsRollups) *NullableDbv0037DiagStatisticsRollups {
	return &NullableDbv0037DiagStatisticsRollups{value: val, isSet: true}
}

func (v NullableDbv0037DiagStatisticsRollups) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDbv0037DiagStatisticsRollups) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


