/*
 * Slurm Rest API
 *
 * API to access and control Slurm DB.
 *
 * API version: dbv0.0.37
 * Contact: sales@schedmd.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmdbrest

import (
	"encoding/json"
)

// Dbv0037JobTres TRES settings
type Dbv0037JobTres struct {
	// TRES list of attributes
	Allocated *[]map[string]interface{} `json:"allocated,omitempty"`
	// TRES list of attributes
	Requested *[]map[string]interface{} `json:"requested,omitempty"`
}

// NewDbv0037JobTres instantiates a new Dbv0037JobTres object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDbv0037JobTres() *Dbv0037JobTres {
	this := Dbv0037JobTres{}
	return &this
}

// NewDbv0037JobTresWithDefaults instantiates a new Dbv0037JobTres object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDbv0037JobTresWithDefaults() *Dbv0037JobTres {
	this := Dbv0037JobTres{}
	return &this
}

// GetAllocated returns the Allocated field value if set, zero value otherwise.
func (o *Dbv0037JobTres) GetAllocated() []map[string]interface{} {
	if o == nil || o.Allocated == nil {
		var ret []map[string]interface{}
		return ret
	}
	return *o.Allocated
}

// GetAllocatedOk returns a tuple with the Allocated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0037JobTres) GetAllocatedOk() (*[]map[string]interface{}, bool) {
	if o == nil || o.Allocated == nil {
		return nil, false
	}
	return o.Allocated, true
}

// HasAllocated returns a boolean if a field has been set.
func (o *Dbv0037JobTres) HasAllocated() bool {
	if o != nil && o.Allocated != nil {
		return true
	}

	return false
}

// SetAllocated gets a reference to the given []map[string]interface{} and assigns it to the Allocated field.
func (o *Dbv0037JobTres) SetAllocated(v []map[string]interface{}) {
	o.Allocated = &v
}

// GetRequested returns the Requested field value if set, zero value otherwise.
func (o *Dbv0037JobTres) GetRequested() []map[string]interface{} {
	if o == nil || o.Requested == nil {
		var ret []map[string]interface{}
		return ret
	}
	return *o.Requested
}

// GetRequestedOk returns a tuple with the Requested field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0037JobTres) GetRequestedOk() (*[]map[string]interface{}, bool) {
	if o == nil || o.Requested == nil {
		return nil, false
	}
	return o.Requested, true
}

// HasRequested returns a boolean if a field has been set.
func (o *Dbv0037JobTres) HasRequested() bool {
	if o != nil && o.Requested != nil {
		return true
	}

	return false
}

// SetRequested gets a reference to the given []map[string]interface{} and assigns it to the Requested field.
func (o *Dbv0037JobTres) SetRequested(v []map[string]interface{}) {
	o.Requested = &v
}

func (o Dbv0037JobTres) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Allocated != nil {
		toSerialize["allocated"] = o.Allocated
	}
	if o.Requested != nil {
		toSerialize["requested"] = o.Requested
	}
	return json.Marshal(toSerialize)
}

type NullableDbv0037JobTres struct {
	value *Dbv0037JobTres
	isSet bool
}

func (v NullableDbv0037JobTres) Get() *Dbv0037JobTres {
	return v.value
}

func (v *NullableDbv0037JobTres) Set(val *Dbv0037JobTres) {
	v.value = val
	v.isSet = true
}

func (v NullableDbv0037JobTres) IsSet() bool {
	return v.isSet
}

func (v *NullableDbv0037JobTres) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDbv0037JobTres(val *Dbv0037JobTres) *NullableDbv0037JobTres {
	return &NullableDbv0037JobTres{value: val, isSet: true}
}

func (v NullableDbv0037JobTres) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDbv0037JobTres) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


