/*
 * Slurm Rest API
 *
 * API to access and control Slurm DB.
 *
 * API version: dbv0.0.37
 * Contact: sales@schedmd.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmdbrest

import (
	"encoding/json"
)

// Dbv0037DiagTime Time values
type Dbv0037DiagTime struct {
	// Average time spent processing this RPC type
	Average *int32 `json:"average,omitempty"`
	// Total time spent processing this RPC type
	Total *int32 `json:"total,omitempty"`
}

// NewDbv0037DiagTime instantiates a new Dbv0037DiagTime object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDbv0037DiagTime() *Dbv0037DiagTime {
	this := Dbv0037DiagTime{}
	return &this
}

// NewDbv0037DiagTimeWithDefaults instantiates a new Dbv0037DiagTime object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDbv0037DiagTimeWithDefaults() *Dbv0037DiagTime {
	this := Dbv0037DiagTime{}
	return &this
}

// GetAverage returns the Average field value if set, zero value otherwise.
func (o *Dbv0037DiagTime) GetAverage() int32 {
	if o == nil || o.Average == nil {
		var ret int32
		return ret
	}
	return *o.Average
}

// GetAverageOk returns a tuple with the Average field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0037DiagTime) GetAverageOk() (*int32, bool) {
	if o == nil || o.Average == nil {
		return nil, false
	}
	return o.Average, true
}

// HasAverage returns a boolean if a field has been set.
func (o *Dbv0037DiagTime) HasAverage() bool {
	if o != nil && o.Average != nil {
		return true
	}

	return false
}

// SetAverage gets a reference to the given int32 and assigns it to the Average field.
func (o *Dbv0037DiagTime) SetAverage(v int32) {
	o.Average = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *Dbv0037DiagTime) GetTotal() int32 {
	if o == nil || o.Total == nil {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0037DiagTime) GetTotalOk() (*int32, bool) {
	if o == nil || o.Total == nil {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *Dbv0037DiagTime) HasTotal() bool {
	if o != nil && o.Total != nil {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *Dbv0037DiagTime) SetTotal(v int32) {
	o.Total = &v
}

func (o Dbv0037DiagTime) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Average != nil {
		toSerialize["average"] = o.Average
	}
	if o.Total != nil {
		toSerialize["total"] = o.Total
	}
	return json.Marshal(toSerialize)
}

type NullableDbv0037DiagTime struct {
	value *Dbv0037DiagTime
	isSet bool
}

func (v NullableDbv0037DiagTime) Get() *Dbv0037DiagTime {
	return v.value
}

func (v *NullableDbv0037DiagTime) Set(val *Dbv0037DiagTime) {
	v.value = val
	v.isSet = true
}

func (v NullableDbv0037DiagTime) IsSet() bool {
	return v.isSet
}

func (v *NullableDbv0037DiagTime) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDbv0037DiagTime(val *Dbv0037DiagTime) *NullableDbv0037DiagTime {
	return &NullableDbv0037DiagTime{value: val, isSet: true}
}

func (v NullableDbv0037DiagTime) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDbv0037DiagTime) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


