/*
 * Slurm Rest API
 *
 * API to access and control Slurm DB.
 *
 * API version: dbv0.0.37
 * Contact: sales@schedmd.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmdbrest

import (
	"encoding/json"
)

// Dbv0037AssociationMaxJobs Max jobs settings
type Dbv0037AssociationMaxJobs struct {
	Per *Dbv0037AssociationMaxJobsPer `json:"per,omitempty"`
}

// NewDbv0037AssociationMaxJobs instantiates a new Dbv0037AssociationMaxJobs object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDbv0037AssociationMaxJobs() *Dbv0037AssociationMaxJobs {
	this := Dbv0037AssociationMaxJobs{}
	return &this
}

// NewDbv0037AssociationMaxJobsWithDefaults instantiates a new Dbv0037AssociationMaxJobs object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDbv0037AssociationMaxJobsWithDefaults() *Dbv0037AssociationMaxJobs {
	this := Dbv0037AssociationMaxJobs{}
	return &this
}

// GetPer returns the Per field value if set, zero value otherwise.
func (o *Dbv0037AssociationMaxJobs) GetPer() Dbv0037AssociationMaxJobsPer {
	if o == nil || o.Per == nil {
		var ret Dbv0037AssociationMaxJobsPer
		return ret
	}
	return *o.Per
}

// GetPerOk returns a tuple with the Per field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0037AssociationMaxJobs) GetPerOk() (*Dbv0037AssociationMaxJobsPer, bool) {
	if o == nil || o.Per == nil {
		return nil, false
	}
	return o.Per, true
}

// HasPer returns a boolean if a field has been set.
func (o *Dbv0037AssociationMaxJobs) HasPer() bool {
	if o != nil && o.Per != nil {
		return true
	}

	return false
}

// SetPer gets a reference to the given Dbv0037AssociationMaxJobsPer and assigns it to the Per field.
func (o *Dbv0037AssociationMaxJobs) SetPer(v Dbv0037AssociationMaxJobsPer) {
	o.Per = &v
}

func (o Dbv0037AssociationMaxJobs) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Per != nil {
		toSerialize["per"] = o.Per
	}
	return json.Marshal(toSerialize)
}

type NullableDbv0037AssociationMaxJobs struct {
	value *Dbv0037AssociationMaxJobs
	isSet bool
}

func (v NullableDbv0037AssociationMaxJobs) Get() *Dbv0037AssociationMaxJobs {
	return v.value
}

func (v *NullableDbv0037AssociationMaxJobs) Set(val *Dbv0037AssociationMaxJobs) {
	v.value = val
	v.isSet = true
}

func (v NullableDbv0037AssociationMaxJobs) IsSet() bool {
	return v.isSet
}

func (v *NullableDbv0037AssociationMaxJobs) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDbv0037AssociationMaxJobs(val *Dbv0037AssociationMaxJobs) *NullableDbv0037AssociationMaxJobs {
	return &NullableDbv0037AssociationMaxJobs{value: val, isSet: true}
}

func (v NullableDbv0037AssociationMaxJobs) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDbv0037AssociationMaxJobs) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


