/*
 * Slurm Rest API
 *
 * API to access and control Slurm DB.
 *
 * API version: dbv0.0.37
 * Contact: sales@schedmd.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmdbrest

import (
	"encoding/json"
)

// Dbv0037QosInfo struct for Dbv0037QosInfo
type Dbv0037QosInfo struct {
	// Slurm errors
	Errors *[]Dbv0037Error `json:"errors,omitempty"`
	// Array of QOS
	Qos *[]Dbv0037Qos `json:"qos,omitempty"`
}

// NewDbv0037QosInfo instantiates a new Dbv0037QosInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDbv0037QosInfo() *Dbv0037QosInfo {
	this := Dbv0037QosInfo{}
	return &this
}

// NewDbv0037QosInfoWithDefaults instantiates a new Dbv0037QosInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDbv0037QosInfoWithDefaults() *Dbv0037QosInfo {
	this := Dbv0037QosInfo{}
	return &this
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *Dbv0037QosInfo) GetErrors() []Dbv0037Error {
	if o == nil || o.Errors == nil {
		var ret []Dbv0037Error
		return ret
	}
	return *o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0037QosInfo) GetErrorsOk() (*[]Dbv0037Error, bool) {
	if o == nil || o.Errors == nil {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *Dbv0037QosInfo) HasErrors() bool {
	if o != nil && o.Errors != nil {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []Dbv0037Error and assigns it to the Errors field.
func (o *Dbv0037QosInfo) SetErrors(v []Dbv0037Error) {
	o.Errors = &v
}

// GetQos returns the Qos field value if set, zero value otherwise.
func (o *Dbv0037QosInfo) GetQos() []Dbv0037Qos {
	if o == nil || o.Qos == nil {
		var ret []Dbv0037Qos
		return ret
	}
	return *o.Qos
}

// GetQosOk returns a tuple with the Qos field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dbv0037QosInfo) GetQosOk() (*[]Dbv0037Qos, bool) {
	if o == nil || o.Qos == nil {
		return nil, false
	}
	return o.Qos, true
}

// HasQos returns a boolean if a field has been set.
func (o *Dbv0037QosInfo) HasQos() bool {
	if o != nil && o.Qos != nil {
		return true
	}

	return false
}

// SetQos gets a reference to the given []Dbv0037Qos and assigns it to the Qos field.
func (o *Dbv0037QosInfo) SetQos(v []Dbv0037Qos) {
	o.Qos = &v
}

func (o Dbv0037QosInfo) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Errors != nil {
		toSerialize["errors"] = o.Errors
	}
	if o.Qos != nil {
		toSerialize["qos"] = o.Qos
	}
	return json.Marshal(toSerialize)
}

type NullableDbv0037QosInfo struct {
	value *Dbv0037QosInfo
	isSet bool
}

func (v NullableDbv0037QosInfo) Get() *Dbv0037QosInfo {
	return v.value
}

func (v *NullableDbv0037QosInfo) Set(val *Dbv0037QosInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableDbv0037QosInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableDbv0037QosInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDbv0037QosInfo(val *Dbv0037QosInfo) *NullableDbv0037QosInfo {
	return &NullableDbv0037QosInfo{value: val, isSet: true}
}

func (v NullableDbv0037QosInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDbv0037QosInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


